#-----------------------------------------------------------------------------------------------------------------
# Example configuration for using an external redis instance instead of the one shipped with spinnaker
#-----------------------------------------------------------------------------------------------------------------
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    service-settings:
      redis:
        overrideBaseUrl: redis://abc.mycompany.com:6379   # External redis endpoint
        skipLifeCycleManagement: true                     # Tell spinnaker to not manage the embedded spin-redis pod
